//jenkinsfile for cd
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
   
        stage('Terraform Init') {
            steps {
                sh 'cd helm-aws/log-message-processor && terraform init'
            }
        }
    
        stage('Terraform Plan') {
            steps {
                sh 'cd helm-aws/log-message-processor && terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'cd helm-aws/log-message-processor && terraform apply -auto-approve tfplan'
            }
        }
    
    }
}