//jenkinsfile for cd
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Clone repository') {
            steps {
                git credentialsId: 'git', url: 'https://github.com/leandrohinz/kubernetes.git'
            }
       
        }
    
        stage('Terraform Init') {
            steps {
                sh 'cd /helm-aws/log-message-processor && terraform init'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'cd /helm-aws/log-message-processor && terraform apply -auto-approve'
            }
        }
    
    }
}