apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-deployment
  namespace: leandrohinestroza
  labels:
    app: todos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: leandrohinz/todos-api:v1
        ports:
        - containerPort: 8082
        env:
        - name: TODO_API_PORT
          value: "8082"
        - name: JWT_SECRET
          value: "foo"
        - name: REDIS_HOST
          value: "redis-service.leandrohinestroza.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log_channel"
---
apiVersion: v1
kind: Service
metadata:
  name: todos-api-service
  namespace: leandrohinestroza
spec:
  type: NodePort
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30003

