apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: leandrohinestroza
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: leandrohinz/frontend:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AUTH_API_ADDRESS
          value: "http://auth-api-service.leandrohinestroza.svc.cluster.local:8000"
        - name: TODOS_API_ADDRESS
          value: "http://todos-api-service.leandrohinestroza.svc.cluster.local:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: leandrohinestroza
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: leandrohinestroza
spec:
  ingressClassName: nginx
  rules:
    - http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: frontend-service
               port:
                 number: 8080
