apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: leandrohinestroza
  labels:
    app: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: leandrohinz/users-api:v1
        ports:
        - containerPort: 8083
        env:
        - name: JWT_SECRET
          value: "foo"
        - name: SERVER_PORT
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: leandrohinestroza
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30004

