apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor-deployment
  namespace: leandrohinestroza
  labels:
    app: log-message-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
      - name: log-message-processor
        image: leandrohinz/log-message-processor:v1
        env:
        - name: REDIS_HOST
          value: "redis-service.leandrohinestroza.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log_channel"
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: log-message-processor-service
#  namespace: leandrohinestroza
#spec:
#  type: NodePort
#  selector:
#    app: log-message-processor
#  ports:
#    - protocol: TCP
#      port: 6379 #preguntar por el container por del lmp o si son todos los puertos
#      targetPort: 6379
#      nodePort: 30004

