apiVersion: v1
kind: Namespace
metadata:
  name: ns-todo-app-k8s-local 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: ns-todo-app-k8s-local
  labels:
    app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: leandrohinz/auth-api:v1
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_API_PORT
          value: "8000"
        - name: USERS_API_ADDRESS
          value: "http://users-api-service.ns-todo-app-k8s-local.svc.cluster.local:8083"
        - name: JWT_SECRET
          value: "foo"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: ns-todo-app-k8s-local
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000

