apiVersion: v1
kind: Namespace
metadata:
  name: ns-ljhh-k8s-local ##Replace this with the name of you namespace.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example-deployment
  namespace: ns-ljhh-k8s-local
  labels:
    app: nginx-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx-example
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example-service
  namespace: ns-ljhh-k8s-local ##Replace this with the name of you namespace.
spec:
  type: NodePort
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

