pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    stage('Clone repository') {
        git credentialsId: 'git', url: 'https://github.com/leandrohinz/kubernetes.git'
    }
    
	stage('Output') {

		def output = sh(returnStdout: true, script: 'ls -al .')
		echo "Output: ${output}"

	}

    stage('Terraform Init') {
        steps {
            sh 'cd /helm-aws/todos-api-chart && terraform init'
        }
    }
    stage('Terraform Apply') {
        steps {
            sh 'cd /helm-aws/todos-api-chart && terraform apply -auto-approve'
        }
    }
    
    }
}